
import sys

sys.stdin.readline() # P2
width, height = map(int, sys.stdin.readline().split()) # W H
sys.stdin.readline() # 255

sys.stdout.write("// Generated by process.py\n\n")
sys.stdout.write("export const fontWidth = %d;\n" % width)
sys.stdout.write("export const fontHeight = %d;\n" % height)
sys.stdout.write("export const fontTexture = new Uint8Array([\n")

for line in sys.stdin:
    items = map(lambda x: "0" if int(x) < 128 else "255", line.strip().split())
    sys.stdout.write(", ".join(items) + ",\n")

sys.stdout.write("]);\n")
